USE WebSiteBaseDB
GO



ALTER DATABASE WebSiteBaseDB SET RECURSIVE_TRIGGERS ON
GO

ALTER DATABASE WebSiteBaseDB SET ANSI_NULLS ON
GO

CREATE MASTER KEY
	ENCRYPTION
	BY PASSWORD = '###a secret password here###';
GO

CREATE CERTIFICATE Cert_Users
	WITH SUBJECT = 'Users'' Credentials';  
GO

CREATE SYMMETRIC KEY SyK_Users
	WITH ALGORITHM = AES_256
	ENCRYPTION
	BY CERTIFICATE Cert_Users;  
GO

CREATE CERTIFICATE Cert_ApiConsumers
	WITH SUBJECT = 'Api Consumers'' Credentials';  
GO

CREATE SYMMETRIC KEY SyK_ApiConsumers
	WITH ALGORITHM = AES_256
	ENCRYPTION
	BY CERTIFICATE Cert_ApiConsumers;  
GO